# $ python -m nwm_routing -f -V3 test_AnA.yaml
#--------------------------------------------------------------------------------
log_parameters:
    #----------
    showtiming: True
    log_level : DEBUG
#--------------------------------------------------------------------------------
network_topology_parameters:
    #----------
    supernetwork_parameters:
        #----------
        geo_file_type: HYFeaturesNetwork  #NHDNetwork 
        geo_file_path: C:/Users/JurgenZach/Documents/Geomodels/Flow-Subsets-CapeCode-2/models/nextgen_01.gpkg
        columns: 
            key: 'id'
            downstream: 'toid'
            dx : 'lengthkm'
            n : 'n'
            ncc : 'nCC'
            s0 : 'So'
            bw : 'BtmWdth'
            waterbody : 'rl_NHDWaterbodyComID'
            #gages : 'rl_gages'
            tw : 'TopWdth'
            twcc : 'TopWdthCC'
            musk : 'MusK'
            musx : 'MusX'
            cs : 'ChSlp'
            alt: 'alt'
        duplicate_wb_segments:
            - 717696
            - 1311881
            - 3133581
            - 1010832
            - 1023120
            - 1813525
            - 1531545
            - 1304859
            - 1320604
            - 1233435
            - 11816
            - 1312051
            - 2723765
            - 2613174
            - 846266
            - 1304891
            - 1233595
            - 1996602
            - 2822462
            - 2384576
            - 1021504
            - 2360642
            - 1326659
            - 1826754
            - 572364
            - 1336910
            - 1332558
            - 1023054
            - 3133527
            - 3053788
            - 3101661
            - 2043487
            - 3056866
            - 1296744
            - 1233515
            - 2045165
            - 1230577
            - 1010164
            - 1031669
            - 1291638
            - 1637751
    waterbody_parameters:
        #----------
        break_network_at_waterbodies: True
        level_pool:
            #----------
            level_pool_waterbody_parameter_file_path: C:/Users/JurgenZach/Documents/Geomodels/Flow-Subsets-CapeCode-2/models/nextgen_01.gpkg
            #NOT THIS: domain/LAKEPARM.nc 
            #reservoir_parameter_file                : C:/Users/JurgenZach/Documents/Geomodels/Flow-Subsets-CapeCode-2/models/nextgen_01.gpkg
        #rfc:
            #----------
            #reservoir_parameter_file                : domain/reservoir_index_AnA.nc
            #reservoir_rfc_forecasts                 : False
            #reservoir_rfc_forecasts_time_series_path: rfc_TimeSeries/
            #reservoir_rfc_forecasts_lookback_hours  : 48
#--------------------------------------------------------------------------------
compute_parameters:
    #----------
    parallel_compute_method: serial #by-subnetwork-jit-clustered #serial 
    compute_kernel         : V02-structured
    assume_short_ts        : True
    subnetwork_target_size : 10000
    cpu_pool               : 36
    restart_parameters:
        start_datetime: 2021-08-23_13:00
    hybrid_parameters:
        run_hybrid_routing: False
    forcing_parameters:
        #----------
        qts_subdivisions            : 12
        dt                          : 300 # [sec]
        qlat_input_folder           : channel_forcing 
        qlat_file_pattern_filter    : "*.CHRTOUT_DOMAIN1"
        coastal_boundary_input_file : #boundary_forcing  
        nts                         : 288 # 288 for 1day; 2592 for 9 days
        max_loop_size               : 24   # [hr]  
    data_assimilation_parameters:
        #----------
        usgs_timeslices_folder   : usgs_TimeSlice/
        usace_timeslices_folder  : usace_TimeSlice/
        timeslice_lookback_hours : 48 
        qc_threshold             : 1
        streamflow_da:
            #----------
            streamflow_nudging            : False
            diffusive_streamflow_nudging  : False
            gage_segID_crosswalk_file     : #domain/RouteLink.nc  
            crosswalk_gage_field          : #'gages'
            crosswalk_segID_field         : #'link'
            wrf_hydro_lastobs_file        : #lastobs/nudgingLastObs.2021-08-23_12:00:00.nc                    
            lastobs_output_folder         : lastobs/
        reservoir_da:
            #----------
            reservoir_persistence_usgs  : False
            reservoir_persistence_usace : False
            gage_lakeID_crosswalk_file  : #domain/reservoir_index_AnA.nc
#--------------------------------------------------------------------------------
output_parameters:
    #----------
    test_output: output/lcr_flowveldepth.pkl
    lite_restart:
        #----------
        lite_restart_output_directory: restart/
    chrtout_output:
        #----------
        wrf_hydro_channel_output_source_folder: channel_forcing/
    chanobs_output:
        #----------
        chanobs_output_directory: output/
        chanobs_filepath        : lcr_chanobs.nc
    lakeout_output: lakeout/
    